### ISSUE TITLE
For whyred (redmi note 5), please.

### ISSUE THREAD

**Issue by 1457384613gh** [multiwirth/aptx-magisk-module-armv7#3]
For whyred (redmi note 5), please.
It can work but that.

**Comment by multiwirth** [comment]
Sorry, what exactly do you mean with "it can work but that" ?
However i cannot support any random device and stock roms as i do not own them and also don´t know anything about their stock roms.
They often use weird implementation of things so there´s not much 
I´m really sorry about that.

The module is designed for aosp or pure stock (like google play editions, nexus or pixel roms) based roms and it will only work if the rom initializes the additional libs added to the system at boot.
It also won´t work on anything **below** android 8.1
Also it´s neccessary for the bluetooth stack implemention to support them.
If the redmi developers created their own bluetooth stuff or heavily modified it, then there´s no chance you´ll get this working.

Flash a compatible rom to your phone if you want to use this module (lineage, AICP etc.) :)
